### ISSUE TITLE
关于内容的困惑

### ISSUE THREAD

**Issue by goldimax** [Seng-Jik/Functional-Magic-Book#1]
1. 前面的部分是用自己构造的语言还是数学符号描述
2. 会细讲F*吗

**Comment by Zhihang-Liu** [comment]
前面的内容绝大多数使用可以跑的F#代码描述。剩余的无类型lambda这部分我会用Racket来完成。
FStar这部分取决于我们的时间安排以及编写时编者的水平。如果是目前的话大概只会提到前面一小部分，毕竟是会出版的书，如果出现了重大失误会很难受

Niltok <notifications@github.com> 于2020年7月1日周三 下午9:49写道：

**Comment by Seng-Jik** [comment]
本书内容面向的是没有接触过函数式编程的新手，因此不会涉及任何进阶的知识，所以应该不会用到F*，除非有必要。

**Comment by ICEYSELF** [comment]
> 本书内容面向的是没有接触过函数式编程的新手，因此不会涉及任何进阶的知识，所以应该不会用到F*，除非有必要。

那么本书面向完全没有接触过编程的新手吗

**Comment by Seng-Jik** [comment]
> > 本书内容面向的是没有接触过函数式编程的新手，因此不会涉及任何进阶的知识，所以应该不会用到F*，除非有必要。
> 
> 那么本书面向完全没有接触过编程的新手吗

是的

**Comment by Zhihang-Liu** [comment]
> 本书内容面向的是没有接触过函数式编程的新手，因此不会涉及任何进阶的知识，所以应该不会用到F*，除非有必要。

你再看看大纲？

**Comment by Seng-Jik** [comment]
> > 本书内容面向的是没有接触过函数式编程的新手，因此不会涉及任何进阶的知识，所以应该不会用到F*，除非有必要。
> 
> 你再看看大纲？

F*不是只在依赖类型的部分才出现吗

**Comment by ICEYSELF** [comment]
> > > 本书内容面向的是没有接触过函数式编程的新手，因此不会涉及任何进阶的知识，所以应该不会用到F*，除非有必要。
> > 
> > 
> > 你再看看大纲？
> 
> F*不是只在依赖类型的部分才出现吗

那Rust和C++呢？

**Comment by ICEYSELF** [comment]
> 那Rust和C++呢？

个人观点，这两门“语言”已经超出了“仅仅讨论程序语言和编程范式”的范畴了，它们或多或少地夹杂了计算机体系结构的一些知识，而如果要讲C++ TMP，甚至还得包含了一些关于C++编译器/C++ standard的内容。我不觉得这些内容能在一章之内讲完。

**Comment by Seng-Jik** [comment]
> > > > 本书内容面向的是没有接触过函数式编程的新手，因此不会涉及任何进阶的知识，所以应该不会用到F*，除非有必要。
> > > 
> > > 
> > > 你再看看大纲？
> > 
> > 
> > F*不是只在依赖类型的部分才出现吗
> 
> 那Rust和C++呢？

C++和Rust仅涉及关于对象生命周期的内容。
