### ISSUE TITLE
关于Lambda Calculus在章节中的位置的问题

### ISSUE THREAD

**Issue by Seng-Jik** [Seng-Jik/Functional-Magic-Book#11]
总的来说尽管 Lambda calculus 是函数和一些其他运算较为基础的形式，并且函数和这些较为基础的运算较为简单，但我并不十分建议先讨论 Lambda calculus 而后扩展到其他内容。我个人倾向于先拿出语言中内建的操作，然后再用 Lambda calculus 重新实现它们。原因如下：

- Lambda calculus 并没有那么简单。尽管规则数很少，但是一下子就理解它们（尤其是理解它的“强大”之处）也需要对计算机领域相当多的了解。
- Lambda calculus 是偏理论性质的内容，放在前面可能会赶走急性子的读者和实用导向的读者；或者他们会干脆跳过这部分去看函数和控制结构。
- Lambda calculus 和后续其他内容（如map, concat, collect, ...）的联系并不紧密。
- 以 Lambda calculus 实现某些数据和控制结构的方式，例如丘奇计数，在现有的计算机架构上是低效的。以 Lambda calculus 开头可能招致一些有部分 C 语言编程经验的读者的怀疑。事实上即便是在 F# 中，本章中讨论的结构也未必是以 Lambda calculus 实现的。

原文 @ICEYSELF

**Comment by Seng-Jik** [comment]
有无具体解决方案。
章节“递归”的开头解释递归时需要有Lambda Calculus的前置知识才可以认知递归函数和一般函数的不同之处。
至于更后面的内容，似乎没有比Lambda Calculus更简单的内容了。
不可能让读者在没有Lambda Calculus的基础下接触Monad、递归和类型。

**Comment by ICEYSELF** [comment]
> 递归函数和一般函数的不同之处

有何不同之处？

**Comment by Zhihang-Liu** [comment]
> > 递归函数和一般函数的不同之处
> 
> 有何不同之处？

即使是从Rust的角度来讲，递归函数的生命周期也和普通函数不同。
同时递归函数不能是闭包

**Comment by ICEYSELF** [comment]
> > > 递归函数和一般函数的不同之处
> > 
> > 
> > 有何不同之处？
> 
> 即使是从Rust的角度来讲，递归函数的生命周期也和普通函数不同。
> 同时递归函数不能是闭包

从Jvav和Racket的角度来讲，我没看出有什么区别。

**Comment by ICEYSELF** [comment]
> 递归函数和一般函数的不同之处

我看到了 `let` 和 `let rec` 的区别，确实这是一个很大的不同点。但是要如何用LC解释letrec的工作原理呢？

**Comment by Seng-Jik** [comment]
> > 递归函数和一般函数的不同之处
> 
> 我看到了 `let` 和 `let rec` 的区别，确实这是一个很大的不同点。但是要如何用LC解释`letrec`的工作原理呢？

let可以直接用LC表示，但let rec并不能，因为let rec后面可能跟一个and，这是LC不能表示的。
