### ISSUE TITLE
作为尝试入过门但没能入进去的 starter 来提几点初学真正的困惑和踩过的坑

### ISSUE THREAD

**Issue by pnck** [Seng-Jik/Functional-Magic-Book#2]
1.   几种纯函数式的语言彼此有什么区别？有类型和无类型有多大差别？
2.  怎样从我们熟悉的 c++ java js python 进入真正的函数式编程？  上面列的语言都支持函数式范式，但它们的函数式短版在哪？为什么有些特性做不到？只要支持 labmda function 都能实现函数式编程范式吗？
3.  既然上述语言都很难实现纯正的函数式，那纯函数式的编程语言，runtime 或 interpreter 是怎么工作的？怎么处理递归、怎么存储、计算惰性求值的表达式？能实现可编译的函数式语言吗？该怎么做？
4.  噢该死的 monad， 图解我看懂了输入几个类型计算出一个新类型，可它到底是咋回事？说白了“类型系统”本质到底是啥，怎样从无类型的 lambda 演算衍生？
5.  从 CPS 到协程，所有语言都想引入的协程跟函数式编程有哪些千丝万缕的联系？

**Comment by Seng-Jik** [comment]
1. 每种语言支持的语言特性都不相同，比如Rust具有生命周期系统、F#和F*具有量纲类型系统，提供了不同的语言特性。有类型的函数式编程语言更容易被编译器检查。
2. 可以试试上手一门从Lisp发展而来的编程语言，如Standard ML、OCaml、Haskell等，C++、Java、Js的问题是并非做不到，而是它们语法噪音较强，但实际上您提到的这些语言都可以进行函数式编程。lambda expression只是函数式编程的一个部分，我们需要借助lambda calculus来讨论函数式编程中各个概念的来源。
3. 编程语言的实现不在本书讨论范围之内，如果您有兴趣的话，可以尝试先实现一个Lisp解释器，之后慢慢完善它，即可了解它们底层的工作方式，当然如果可能的话，尽可能还是使用函数式的方式来实现它。
4. Monad您可以把它看成是一个盒子，这个盒子包裹了一个值，然后您可以通过一个bind的函数把里面的值取出来做一些运算，并生成一个新的盒子，用大白话的方法解释就是如此。您可以使用Monad来模拟状态、规定IO的计算顺序等。具体内容可以等待本书对于Monad的介绍。
5. 协程可以看作是一个“可以随时中断并继续”的程序，对于这种程序，我们需要一个概念来表示“接下来要做的事情”，于是就有了continuation，我们用“continuation”来表示“接下来要做什么”。现在我们可以将continuation传给一个操作，让这个操作结束后自行调用“continuation”，这就是CPS了。

**Comment by Zhihang-Liu** [comment]
@pnck 关于类型系统，我会在第二章和第六章的区间中给出答案，即如何从无类型lambda演算扩展到简单类型lambda演算。当然，二到六章的顺序目前看来急需调整 @Seng-Jik ，根据Chuigda·Whitegive给出的建议，我们需要在这几章中由expression（手指算数）到Function再到Lambda，最后再讲类型。而目前为止Lambda过于靠前了，代数数据类型和“类型”这两章中间夹杂了一章递归。有一说一，很割裂。我能理解你想在递归中讲一些数据结构的处理，这个思路是没错的。但还是那句话，太割裂了，我们应该在递归中稍微讲一些adt（但不讲它们是啥），然后把代数数据类型和类型这一章合并起来。

**Comment by Zhihang-Liu** [comment]
补充， @ICEYSELF

**Comment by pnck** [comment]
其实我提这几个问题是想能在书里看到，并且能以比较系统的知识结构来学习它们。期待能从书中内容的自然条理中覆盖到上述部分问题。

比如引子先从（我看见不少教程都）js 入手，然后探讨一下“响应式”的本质，再过渡到 lambda 演算
比如专门抽一章来讲函数式语言的 runtime 需要有什么额外设计
比如在讲解一下函数式中的特殊构造与用它们“模拟”更直觉的编程语言系统的思路和关系，比如 io、副作用、oo、协程  啥的

我学习的思维方式和结构不一定适合所有人也不一定要影响哪个教材书籍的撰写思路，只是碰巧有机会就提一下而已，酌情吸取

**Comment by Zhihang-Liu** [comment]
感谢提议。也许我们会在工程实践前抽一章“真实世界的函数式编程”来专门讲IO、副作用和RAII

**Comment by goldimax** [comment]
顺便，函数式思维也会是萌新在学习时的困惑。

**Comment by Zhihang-Liu** [comment]
关于语言，为了照顾零基础的读者，同时也让思维转换更清晰，目前我的决定是基本每个代码的例子都给出Racket和F#这两个语言的示例。
同时要求所有的代码都可以跑，不写伪代码。
这样就会导致某些情况会有Racket能跑而F#不能跑（比如Untyped Lambda），某些情况下F#能跑而Racket不能跑（比如adt那一章的某些例子）

**Comment by ICEYSELF** [comment]
Typed的部分也许可以用Racket来做，我们最好问问番茄酱拌面。
